import type {
  BoundaryProperties,
  EarthquakeProperties,
  FeatureCollection,
  HistoryMoment,
  LineGeometry,
  PointGeometry,
  SourceStatusResponse,
  StoryChapter,
  TsunamiProperties,
  VolcanoProfile,
  VolcanoProperties,
} from "@/lib/types";

const GVP = "https://volcano.si.edu/";
const fixtureRefreshedAt = "2026-07-15T00:00:00Z";
const gvpSource = { dataset: "GVP volcanoes", authority: "Smithsonian Global Volcanism Program", version: "5.3.6 fixture", url: "https://volcano.si.edu/database/webservices.cfm", publishedAt: "2026-05-26", refreshedAt: fixtureRefreshedAt };
const usgsEventSource = { dataset: "USGS earthquake catalog", authority: "U.S. Geological Survey", version: "FDSN/GeoJSON", url: "https://earthquake.usgs.gov/fdsnws/event/1/", refreshedAt: fixtureRefreshedAt };
const usgsBoundarySource = { dataset: "USGS plate boundaries", authority: "U.S. Geological Survey", version: "ArcGIS layer 1", url: "https://earthquake.usgs.gov/arcgis/rest/services/eq/map_plateboundaries/MapServer/1", refreshedAt: fixtureRefreshedAt };
const noaaSource = { dataset: "Global Historical Tsunami Database", authority: "NOAA/NCEI", version: "historical event export", url: "https://www.ncei.noaa.gov/products/worldwide-tsunami-database", refreshedAt: fixtureRefreshedAt };

export const storyChapters: StoryChapter[] = [
  {
    id: "aotearoa",
    kicker: "01 · Our narrative origin",
    title: "New Zealand → Kermadec → Tonga",
    range: "35°S — 20°S",
    body: "We begin in Aotearoa by editorial choice, not geological law. The Pacific Plate descends westward along the Kermadec–Tonga trench, feeding an arc that includes Taupō and the submarine volcanoes north of New Zealand.",
    boundary: "Subduction · Pacific beneath Australian plate",
    evidence: "Volcano locations are GVP records; the route is an editorial guide.",
    center: [179, -30],
    zoom: 3.25,
    volcanoSlugs: ["taupo", "hunga-tonga-hunga-haapai"],
  },
  {
    id: "southwest",
    kicker: "02 · Complicated margins",
    title: "Southwest Pacific → Philippines",
    range: "10°S — 18°N",
    body: "Island arcs bend around microplates and collision zones. The Philippines sits where several trenches and fault systems meet; Mayon’s near-symmetry is only the surface expression of a much less tidy setting.",
    boundary: "Subduction, collision, and strike-slip systems",
    evidence: "Plate lines simplify broad boundary zones; they are not exact faults.",
    center: [136, 8],
    zoom: 3.1,
    volcanoSlugs: ["mayon"],
  },
  {
    id: "northwest",
    kicker: "03 · The long northern arc",
    title: "Japan → Kurils → Kamchatka",
    range: "31°N — 57°N",
    body: "The route turns through Japan and the Kuril–Kamchatka arc. Offshore subduction builds volcanic chains, while large earthquakes can abruptly displace the seafloor—as the 2011 Tōhoku event showed.",
    boundary: "Pacific plate subduction beneath Okhotsk and Amur margins",
    evidence: "Nearby boundaries provide context, never causal attribution for a point.",
    center: [151, 43],
    zoom: 3.05,
    volcanoSlugs: ["fuji", "klyuchevskoy"],
  },
  {
    id: "northeast",
    kicker: "04 · Across the dateline",
    title: "Aleutians → Alaska → Cascadia",
    range: "55°N — 40°N",
    body: "The Aleutian chain sweeps east into Alaska, then the margin changes character along Cascadia. Volcanic peaks sit inland of the trench; transform motion dominates farther south along California.",
    boundary: "Subduction transitions toward transform motion",
    evidence: "The International Date Line is a map seam, not a break in the system.",
    center: [-150, 51],
    zoom: 3.05,
    volcanoSlugs: ["mount-st-helens"],
  },
  {
    id: "mesoamerica",
    kicker: "05 · A continental chain",
    title: "Mexico → Central America",
    range: "20°N — 10°N",
    body: "The Cocos Plate sinks beneath North America and the Caribbean, sustaining a dense line of frequently active volcanoes from central Mexico through Guatemala and beyond.",
    boundary: "Cocos plate subduction",
    evidence: "Activity changes through time; this atlas is educational, not an alert service.",
    center: [-96, 15],
    zoom: 3.8,
    volcanoSlugs: ["popocatepetl", "fuego"],
  },
  {
    id: "andes",
    kicker: "06 · The eastern return",
    title: "The Andes",
    range: "5°N — 45°S",
    body: "Along South America, the Nazca Plate descends beneath the continent. Gaps and clusters in Andean volcanism reflect changes in slab angle, crust, and magma pathways—not a continuous wall of fire.",
    boundary: "Nazca plate subduction beneath South America",
    evidence: "Our journey ends here; the geology does not.",
    center: [-72, -20],
    zoom: 3.25,
    volcanoSlugs: ["nevado-del-ruiz", "villarrica"],
  },
];

export const volcanoProfiles: VolcanoProfile[] = [
  {
    volcanoNumber: 241070,
    slug: "taupo",
    name: "Taupō",
    localName: "Taupō-nui-a-Tia",
    country: "New Zealand",
    region: "New Zealand",
    volcanoType: "Caldera",
    elevationM: 760,
    lastKnownEruption: "c. 260 CE (GVP database year)",
    confidence: "authoritative",
    source: gvpSource,
    position: [175.57, -38.82],
    dek: "A vast rhyolitic caldera, visible today as lake and landscape rather than a single cone.",
    introduction: "Taupō challenges the familiar silhouette of a volcano. Much of the caldera is occupied by Lake Taupō, and its explosive history is read through deposits spread across New Zealand.",
    tectonicSetting: "Central Taupō Volcanic Zone, above the Hikurangi–Kermadec subduction system.",
    membershipNote: "Included in the current Smithsonian Pacific Ring of Fire region set.",
    notableEruptions: [{ year: 232, label: "Taupō eruption", detail: "A very large explosive eruption; calendar age remains an area of scientific refinement.", precision: "range" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=241070` }],
  },
  {
    volcanoNumber: 243040,
    slug: "hunga-tonga-hunga-haapai",
    name: "Hunga Tonga–Hunga Haʻapai",
    country: "Tonga",
    region: "Tonga Islands",
    volcanoType: "Caldera",
    elevationM: 114,
    lastKnownEruption: "2022",
    confidence: "authoritative",
    source: gvpSource,
    position: [-175.38, -20.54],
    dek: "A mostly submarine caldera whose 2022 eruption sent pressure waves around the planet.",
    introduction: "The small islands visible before 2022 were fragments of a much larger submarine volcanic system. Its eruption demonstrated how atmosphere, ocean, and volcano can couple at global scale.",
    tectonicSetting: "Tonga–Kermadec arc, west of one of Earth’s deepest and fastest subduction zones.",
    membershipNote: "Included in the Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 2022, label: "15 January climax", detail: "Explosive eruption, atmospheric waves, and a destructive trans-oceanic tsunami.", precision: "day" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=243040` }],
  },
  {
    volcanoNumber: 273030,
    slug: "mayon",
    name: "Mayon",
    country: "Philippines",
    region: "Luzon",
    volcanoType: "Stratovolcano",
    elevationM: 2462,
    lastKnownEruption: "2026",
    confidence: "authoritative",
    source: gvpSource,
    position: [123.685, 13.257],
    dek: "An exceptionally symmetrical cone built by repeated lava flows and explosive eruptions.",
    introduction: "Mayon’s celebrated form records persistence, not simplicity. Pyroclastic flows, lahars, lava, and ash have repeatedly affected communities around its base.",
    tectonicSetting: "Bicol volcanic arc associated with westward subduction along the Philippine Trench system.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 1814, label: "Cagsawa eruption", detail: "A destructive explosive eruption remembered through deposits and surviving structures.", precision: "year" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=273030` }],
  },
  {
    volcanoNumber: 283030,
    slug: "fuji",
    name: "Fuji",
    country: "Japan",
    region: "Honshu",
    volcanoType: "Stratovolcano",
    elevationM: 3776,
    lastKnownEruption: "1707–1708",
    confidence: "authoritative",
    source: gvpSource,
    position: [138.731, 35.361],
    dek: "Japan’s highest mountain, a young composite cone built over older volcanic centers.",
    introduction: "Fuji is an icon and an active volcano. The Hōei eruption opened vents on its flank and carried ash east toward Edo, showing that a quiet profile is not a forecast.",
    tectonicSetting: "Near the junction of the Philippine Sea, Amur, and Okhotsk plate domains.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 1707, label: "Hōei eruption", detail: "A flank eruption with widespread tephra fall; exact impacts vary by historical source.", precision: "range" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=283030` }],
  },
  {
    volcanoNumber: 300260,
    slug: "klyuchevskoy",
    name: "Klyuchevskoy",
    country: "Russia",
    region: "Kamchatka",
    volcanoType: "Stratovolcano",
    elevationM: 4754,
    lastKnownEruption: "2025",
    confidence: "authoritative",
    source: gvpSource,
    position: [160.642, 56.056],
    dek: "A towering, persistently active basaltic-andesitic cone on the Kamchatka Peninsula.",
    introduction: "Klyuchevskoy rises within one of the planet’s most volcanically active clusters. Frequent activity makes its ‘last eruption’ field especially sensitive to dataset freshness.",
    tectonicSetting: "Kuril–Kamchatka arc above northwest Pacific subduction.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 2023, label: "Recent eruptive episode", detail: "Activity records can be revised; consult the source for current status.", precision: "year" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=300260` }],
  },
  {
    volcanoNumber: 321050,
    slug: "mount-st-helens",
    name: "Mount St. Helens",
    country: "United States",
    region: "Cascades",
    volcanoType: "Stratovolcano",
    elevationM: 2549,
    lastKnownEruption: "2008",
    confidence: "authoritative",
    source: gvpSource,
    position: [-122.18, 46.2],
    dek: "The 1980 lateral blast transformed a Cascade peak and modern volcanology.",
    introduction: "A magnitude 5.1 earthquake triggered collapse of the unstable north flank on 18 May 1980. The resulting depressurization produced a lateral blast—not a conventional vertical eruption alone.",
    tectonicSetting: "Cascade arc above Juan de Fuca plate subduction beneath North America.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 1980, label: "18 May eruption", detail: "Landslide, lateral blast, ash column, and lahars caused severe regional impacts.", precision: "day" }],
    sources: [{ label: "USGS volcano overview", href: "https://www.usgs.gov/volcanoes/mount-st.-helens" }, { label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=321050` }],
  },
  {
    volcanoNumber: 341090,
    slug: "popocatepetl",
    name: "Popocatépetl",
    country: "Mexico",
    region: "Mexico",
    volcanoType: "Stratovolcano",
    elevationM: 5393,
    lastKnownEruption: "2026",
    confidence: "authoritative",
    source: gvpSource,
    position: [-98.622, 19.023],
    dek: "A glacier-fringed active volcano near one of the world’s largest urban regions.",
    introduction: "Popocatépetl’s frequent emissions and explosions are closely monitored. This atlas records historical and geographic context; official observatories provide current hazard information.",
    tectonicSetting: "Trans-Mexican Volcanic Belt, related to Cocos plate subduction.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 1994, label: "Renewed activity", detail: "A new period of activity began after decades of relative quiet and continues episodically.", precision: "year" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=341090` }],
  },
  {
    volcanoNumber: 342090,
    slug: "fuego",
    name: "Fuego",
    country: "Guatemala",
    region: "Guatemala",
    volcanoType: "Stratovolcano",
    elevationM: 3799,
    lastKnownEruption: "2026",
    confidence: "authoritative",
    source: gvpSource,
    position: [-90.88, 14.473],
    dek: "One of Central America’s most active volcanoes, immediately beside Acatenango.",
    introduction: "Fuego’s short-lived explosions can coexist with more dangerous pyroclastic flows and lahars. The deadly 2018 eruption makes clear why visible activity alone is an incomplete guide to impact.",
    tectonicSetting: "Central American volcanic arc above Cocos plate subduction.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 2018, label: "3 June eruption", detail: "Pyroclastic density currents caused major loss of life; totals vary by accounting method.", precision: "day" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=342090` }],
  },
  {
    volcanoNumber: 351020,
    slug: "nevado-del-ruiz",
    name: "Nevado del Ruiz",
    country: "Colombia",
    region: "Northern Andes",
    volcanoType: "Stratovolcano",
    elevationM: 5279,
    lastKnownEruption: "2026",
    confidence: "authoritative",
    source: gvpSource,
    position: [-75.324, 4.892],
    dek: "An ice-capped Andean volcano whose 1985 lahars devastated Armero.",
    introduction: "The 1985 eruption was moderate in size, but hot material melted snow and ice. Lahars traveled far down river valleys—an example of how impact is not reducible to eruption magnitude.",
    tectonicSetting: "Northern Volcanic Zone of the Andes above Nazca plate subduction.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 1985, label: "Armero tragedy", detail: "Lahars caused catastrophic loss of life after the 13 November eruption.", precision: "day" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=351020` }],
  },
  {
    volcanoNumber: 357120,
    slug: "villarrica",
    name: "Villarrica",
    country: "Chile",
    region: "Southern Andes",
    volcanoType: "Stratovolcano",
    elevationM: 2847,
    lastKnownEruption: "2025",
    confidence: "authoritative",
    source: gvpSource,
    position: [-71.93, -39.42],
    dek: "A persistently active, snow-covered cone with a frequently observed lava lake.",
    introduction: "Villarrica combines frequent small activity with the potential for ice-melt lahars. Its changing summit conditions are monitored by Chilean authorities.",
    tectonicSetting: "Southern Volcanic Zone of the Andes above Nazca plate subduction.",
    membershipNote: "Included in the current Smithsonian PROF regional definition.",
    notableEruptions: [{ year: 2015, label: "3 March eruption", detail: "A brief lava-fountain episode prompted evacuations and generated small lahars.", precision: "day" }],
    sources: [{ label: "Smithsonian GVP profile", href: `${GVP}volcano.cfm?vn=357120` }],
  },
];

const fallbackMeta = (count: number, sourceDataset: string, sourceUrl: string) => ({
  count,
  limit: 1000,
  offset: 0,
  sourceDataset,
  generatedAt: fixtureRefreshedAt,
  isFallback: true as const,
  sourceUrl,
  notice: "The live API is unavailable. Showing a small, sourced demonstration subset.",
});

export const fallbackVolcanoes: FeatureCollection<PointGeometry, VolcanoProperties> = {
  type: "FeatureCollection",
  meta: fallbackMeta(volcanoProfiles.length, "gvp-volcanoes", "https://volcano.si.edu/database/webservices.cfm"),
  features: volcanoProfiles.map((volcano) => ({
    type: "Feature",
    id: volcano.volcanoNumber,
    geometry: { type: "Point", coordinates: volcano.position },
    properties: {
      volcanoNumber: volcano.volcanoNumber,
      slug: volcano.slug,
      name: volcano.name,
      country: volcano.country,
      region: volcano.region,
      volcanoType: volcano.volcanoType,
      elevationM: volcano.elevationM,
      lastKnownEruption: volcano.lastKnownEruption,
      confidence: volcano.confidence,
      source: volcano.source,
    },
  })),
};

export const fallbackEarthquakes: FeatureCollection<PointGeometry, EarthquakeProperties> = {
  type: "FeatureCollection",
  meta: fallbackMeta(4, "usgs-earthquakes", "https://earthquake.usgs.gov/fdsnws/event/1/"),
  features: [
    { id: "demo-nz", position: [179.3, -29.2], magnitude: 5.2, depthKm: 35, place: "Kermadec Islands region" },
    { id: "demo-jp", position: [143.6, 38.1], magnitude: 5.8, depthKm: 28, place: "Off east coast of Honshu" },
    { id: "demo-ak", position: [-164.4, 53.2], magnitude: 5.1, depthKm: 44, place: "Fox Islands, Aleutians" },
    { id: "demo-cl", position: [-72.1, -30.4], magnitude: 5.5, depthKm: 61, place: "Coquimbo, Chile" },
  ].map((item) => ({
    type: "Feature" as const,
    id: item.id,
    geometry: { type: "Point" as const, coordinates: item.position as [number, number] },
    properties: { eventId: item.id, place: item.place, magnitude: item.magnitude, depthKm: item.depthKm, occurredAt: "2026-07-15T00:00:00Z", status: "demo fixture", source: usgsEventSource },
  })),
};

export const fallbackBoundaries: FeatureCollection<LineGeometry, BoundaryProperties> = {
  type: "FeatureCollection",
  meta: fallbackMeta(4, "usgs-plate-boundaries", "https://earthquake.usgs.gov/arcgis/rest/services/eq/map_plateboundaries/MapServer/1"),
  features: [
    { id: "tonga", name: "Tonga–Kermadec trench", type: "convergent", coordinates: [[178, -38], [-177, -30], [-175, -20], [-174, -15]] },
    { id: "japan", name: "Japan–Kuril–Kamchatka margin", type: "convergent", coordinates: [[142, 31], [145, 40], [153, 48], [163, 56]] },
    { id: "aleutian", name: "Aleutian trench", type: "convergent", coordinates: [[170, 52], [178, 51], [-170, 52], [-150, 57]] },
    { id: "americas", name: "Eastern Pacific convergent margins", type: "convergent", coordinates: [[-124, 47], [-104, 20], [-90, 13], [-79, 4], [-72, -18], [-74, -44]] },
  ].map((item) => ({
    type: "Feature" as const,
    id: item.id,
    geometry: { type: "LineString" as const, coordinates: item.coordinates as [number, number][] },
    properties: { boundaryId: item.id, name: item.name, boundaryType: item.type as "convergent", confidence: "editorial" as const, source: usgsBoundarySource },
  })),
};

export const fallbackTsunamis: FeatureCollection<PointGeometry, TsunamiProperties> = {
  type: "FeatureCollection",
  meta: fallbackMeta(3, "noaa-tsunamis", "https://www.ncei.noaa.gov/products/worldwide-tsunami-database"),
  features: [
    { eventId: "1960-valdivia", place: "Southern Chile", year: 1960, cause: "Earthquake", position: [-73.05, -38.14], height: 25, deaths: 1655 },
    { eventId: "2011-tohoku", place: "Tōhoku, Japan", year: 2011, cause: "Earthquake", position: [142.37, 38.3], height: 40.5, deaths: 18500 },
    { eventId: "2022-hunga", place: "Tonga", year: 2022, cause: "Volcanic eruption", position: [-175.38, -20.54], height: 22, deaths: 6 },
  ].map((item) => ({
    type: "Feature" as const,
    id: item.eventId,
    geometry: { type: "Point" as const, coordinates: item.position as [number, number] },
    properties: { eventId: item.eventId, place: item.place, year: item.year, cause: item.cause, maxWaterHeightM: item.height, deaths: item.deaths, confidence: "uncertain" as const, source: noaaSource },
  })),
};

export const historyMoments: HistoryMoment[] = [
  {
    id: "tambora",
    year: "1815",
    title: "Tambora",
    place: "Sumbawa, present-day Indonesia",
    kind: "eruption",
    measured: "GVP records a VEI 7 eruption and extensive caldera formation.",
    interpretation: "Its atmospheric effects make Tambora central to global eruption history, even though Smithsonian’s current Pacific Ring of Fire region set largely excludes Indonesia.",
    uncertainty: "Early nineteenth-century mortality estimates combine direct and indirect effects and vary by source.",
    sourceLabel: "Smithsonian GVP · Tambora",
    sourceUrl: "https://volcano.si.edu/volcano.cfm?vn=264040",
  },
  {
    id: "krakatau",
    year: "1883",
    title: "Krakatau",
    place: "Sunda Strait, Indonesia",
    kind: "eruption",
    measured: "Explosions and sector collapse generated destructive tsunamis around the Sunda Strait.",
    interpretation: "The event connects volcanic processes, ocean displacement, and worldwide communication history.",
    uncertainty: "Historical run-up and fatality numbers differ among reconstructions and administrative records.",
    sourceLabel: "Smithsonian GVP · Krakatau",
    sourceUrl: "https://volcano.si.edu/volcano.cfm?vn=262000",
  },
  {
    id: "valdivia",
    year: "1960",
    title: "Valdivia",
    place: "Southern Chile",
    kind: "earthquake + tsunami",
    measured: "USGS lists moment magnitude 9.5, the largest instrumentally recorded earthquake.",
    interpretation: "The Pacific-wide tsunami revealed how a rupture on one continental margin becomes an ocean-basin event.",
    uncertainty: "Deaths and wave heights are location-dependent; database totals are revised as records improve.",
    sourceLabel: "USGS · 1960 Chile earthquake",
    sourceUrl: "https://www.usgs.gov/programs/earthquake-hazards/science/20-largest-earthquakes-world",
  },
  {
    id: "st-helens",
    year: "1980",
    title: "Mount St. Helens",
    place: "Washington, United States",
    kind: "eruption",
    measured: "A magnitude 5.1 earthquake preceded a giant landslide and lateral blast on 18 May.",
    interpretation: "The event changed how scientists and publics visualize flank collapse and directed blasts.",
    uncertainty: "Deposit volumes and energy estimates depend on model and measurement method.",
    sourceLabel: "USGS · Mount St. Helens 1980",
    sourceUrl: "https://www.usgs.gov/volcanoes/mount-st.-helens/science/1980-cataclysmic-eruption",
  },
  {
    id: "pinatubo",
    year: "1991",
    title: "Pinatubo",
    place: "Luzon, Philippines",
    kind: "eruption",
    measured: "The climactic eruption injected a large sulfur dioxide mass into the stratosphere.",
    interpretation: "Successful monitoring and evacuation are as important to its story as the globally observed atmospheric response.",
    uncertainty: "Climate response estimates separate volcanic forcing from simultaneous natural variability.",
    sourceLabel: "USGS · Pinatubo",
    sourceUrl: "https://www.usgs.gov/volcanoes/pinatubo/science/1991-eruption-mount-pinatubo",
  },
  {
    id: "tohoku",
    year: "2011",
    title: "Tōhoku",
    place: "Northeastern Japan",
    kind: "earthquake + tsunami",
    measured: "A magnitude 9.1 megathrust earthquake generated a devastating tsunami on 11 March.",
    interpretation: "Its consequences crossed geology, engineering, infrastructure, and long-term displacement.",
    uncertainty: "Impact totals change by whether missing people and disaster-related deaths are included.",
    sourceLabel: "USGS · Tōhoku earthquake",
    sourceUrl: "https://earthquake.usgs.gov/earthquakes/eventpage/official20110311054624120_30/executive",
  },
  {
    id: "hunga",
    year: "2022",
    title: "Hunga Tonga–Hunga Haʻapai",
    place: "Tonga",
    kind: "eruption",
    measured: "The 15 January explosion generated atmospheric waves, ash, and a trans-oceanic tsunami.",
    interpretation: "The eruption expanded scientific attention to air–sea coupling and non-earthquake tsunami generation.",
    uncertainty: "Peak plume height and energy have been refined across multiple satellite and model studies.",
    sourceLabel: "Smithsonian GVP · Hunga Tonga",
    sourceUrl: "https://volcano.si.edu/volcano.cfm?vn=243040",
  },
];

export const fallbackSourceStatus: SourceStatusResponse = {
  generatedAt: "2026-07-15T00:00:00Z",
  disclaimer: "Demonstration fixture. Live source freshness is unavailable.",
  datasets: [
    { key: "gvp", name: "Smithsonian Global Volcanism Program", authority: "Smithsonian Institution", version: "5.3.6 pinned membership fixture", publishedAt: "2026-05-26", lastSuccessfulRunAt: fixtureRefreshedAt, refreshCadence: "Weekly", membershipReviewStatus: "approved", sourceUrl: "https://volcano.si.edu/database/webservices.cfm", license: { name: "GVP data use terms", url: "https://volcano.si.edu/about/citation.cfm" }, metadata: { fallback: true } },
    { key: "usgs-events", name: "USGS Earthquake Catalog", authority: "U.S. Geological Survey", version: "GeoJSON/FDSN", publishedAt: null, lastSuccessfulRunAt: fixtureRefreshedAt, refreshCadence: "5 min + daily reconciliation", membershipReviewStatus: null, sourceUrl: "https://earthquake.usgs.gov/fdsnws/event/1/", license: { name: "U.S. government public domain", url: "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits" }, metadata: { fallback: true } },
    { key: "usgs-plates", name: "USGS Plate Boundaries", authority: "U.S. Geological Survey", version: "ArcGIS MapServer layer 1", publishedAt: null, lastSuccessfulRunAt: fixtureRefreshedAt, refreshCadence: "Monthly", membershipReviewStatus: null, sourceUrl: "https://earthquake.usgs.gov/arcgis/rest/services/eq/map_plateboundaries/MapServer/1", license: { name: "U.S. government public domain", url: "https://www.usgs.gov/information-policies-and-instructions/copyrights-and-credits" }, metadata: { fallback: true } },
    { key: "noaa-tsunami", name: "NOAA/WDS Global Historical Tsunami Database", authority: "NOAA/NCEI", version: "event export", publishedAt: null, lastSuccessfulRunAt: fixtureRefreshedAt, refreshCadence: "Monthly", membershipReviewStatus: null, sourceUrl: "https://www.ncei.noaa.gov/products/worldwide-tsunami-database", license: { name: "NOAA data access terms", url: "https://www.noaa.gov/disclaimer" }, metadata: { fallback: true } },
  ],
};

export const volcanoBySlug = new Map(volcanoProfiles.map((volcano) => [volcano.slug, volcano]));
