CREATE EXTENSION IF NOT EXISTS postgis;
--;;
CREATE EXTENSION IF NOT EXISTS pg_trgm;
--;;
CREATE EXTENSION IF NOT EXISTS btree_gist;
--;;

CREATE SCHEMA IF NOT EXISTS ops;
--;;
CREATE SCHEMA IF NOT EXISTS core;
--;;
CREATE SCHEMA IF NOT EXISTS analytics;
--;;

CREATE TABLE IF NOT EXISTS ops.source_dataset (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key               TEXT NOT NULL UNIQUE,
    display_name             TEXT NOT NULL,
    authority                TEXT NOT NULL,
    source_url               TEXT NOT NULL,
    license_name             TEXT,
    license_url              TEXT,
    refresh_cadence          TEXT NOT NULL,
    current_version          TEXT,
    current_published_at     TIMESTAMPTZ,
    last_successful_run_at   TIMESTAMPTZ,
    expected_record_count    INTEGER,
    expected_region_count    INTEGER,
    membership_review_status TEXT NOT NULL DEFAULT 'not_applicable',
    metadata                 JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT source_membership_review_status
      CHECK (membership_review_status IN ('not_applicable', 'approved', 'review_required'))
);
--;;

CREATE TABLE IF NOT EXISTS ops.ingestion_run (
    id                    UUID PRIMARY KEY,
    source_dataset_id     BIGINT NOT NULL REFERENCES ops.source_dataset(id),
    status                TEXT NOT NULL,
    upstream_version      TEXT,
    upstream_published_at TIMESTAMPTZ,
    started_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at           TIMESTAMPTZ,
    fetched_count         INTEGER,
    staged_count          INTEGER,
    activated_count       INTEGER,
    rejected_count        INTEGER NOT NULL DEFAULT 0,
    checksum_sha256       TEXT,
    error_class           TEXT,
    error_message         TEXT,
    validation_report     JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT ingestion_status
      CHECK (status IN ('running', 'succeeded', 'failed', 'skipped_locked'))
);
--;;

CREATE INDEX IF NOT EXISTS ingestion_run_source_started_idx
    ON ops.ingestion_run (source_dataset_id, started_at DESC);
--;;

CREATE TABLE IF NOT EXISTS ops.ingestion_staging (
    ingestion_run_id UUID NOT NULL REFERENCES ops.ingestion_run(id) ON DELETE CASCADE,
    record_type      TEXT NOT NULL,
    upstream_id      TEXT NOT NULL,
    normalized_record JSONB NOT NULL,
    staged_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ingestion_run_id, record_type, upstream_id)
);
--;;

CREATE TABLE IF NOT EXISTS ops.ingestion_rejection (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingestion_run_id UUID NOT NULL REFERENCES ops.ingestion_run(id) ON DELETE CASCADE,
    upstream_id      TEXT,
    reason           TEXT NOT NULL,
    raw_record       JSONB NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
--;;

CREATE TABLE IF NOT EXISTS core.volcanic_region (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region_number      INTEGER,
    name               TEXT NOT NULL,
    slug               TEXT NOT NULL UNIQUE,
    parent_region_name TEXT,
    prof_region        BOOLEAN NOT NULL DEFAULT false,
    story_order        INTEGER,
    geom               geometry(MultiPolygon, 4326),
    source_dataset_id  BIGINT REFERENCES ops.source_dataset(id),
    source_version     TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
--;;

CREATE INDEX IF NOT EXISTS volcanic_region_geom_gix
    ON core.volcanic_region USING gist (geom);
--;;

CREATE TABLE IF NOT EXISTS core.volcano (
    volcano_number       INTEGER PRIMARY KEY,
    name                 TEXT NOT NULL,
    slug                 TEXT NOT NULL UNIQUE,
    country              TEXT,
    subregion            TEXT,
    volcanic_region_id   BIGINT REFERENCES core.volcanic_region(id),
    primary_volcano_type TEXT,
    tectonic_setting     TEXT,
    evidence_category    TEXT,
    elevation_m          INTEGER,
    last_eruption_year   INTEGER,
    description          TEXT,
    geom                 geometry(Point, 4326) NOT NULL,
    source_dataset_id    BIGINT REFERENCES ops.source_dataset(id),
    source_version       TEXT NOT NULL,
    source_updated_at    TIMESTAMPTZ,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT volcano_longitude CHECK (ST_X(geom) BETWEEN -180 AND 180),
    CONSTRAINT volcano_latitude CHECK (ST_Y(geom) BETWEEN -90 AND 90)
);
--;;

CREATE INDEX IF NOT EXISTS volcano_geom_gix ON core.volcano USING gist (geom);
--;;
CREATE INDEX IF NOT EXISTS volcano_name_trgm_idx ON core.volcano USING gin (name gin_trgm_ops);
--;;
CREATE INDEX IF NOT EXISTS volcano_region_idx ON core.volcano (volcanic_region_id);
--;;

CREATE TABLE IF NOT EXISTS core.ring_membership (
    volcano_number     INTEGER NOT NULL REFERENCES core.volcano(volcano_number) ON DELETE CASCADE,
    definition_key     TEXT NOT NULL,
    dataset_version    TEXT NOT NULL,
    included           BOOLEAN NOT NULL,
    inclusion_reason   TEXT NOT NULL,
    confidence         TEXT NOT NULL DEFAULT 'authoritative',
    reviewed_at        TIMESTAMPTZ,
    source_dataset_id  BIGINT REFERENCES ops.source_dataset(id),
    PRIMARY KEY (volcano_number, definition_key, dataset_version),
    CONSTRAINT ring_membership_confidence
      CHECK (confidence IN ('authoritative', 'editorial', 'uncertain'))
);
--;;

CREATE INDEX IF NOT EXISTS ring_membership_current_idx
    ON core.ring_membership (definition_key, dataset_version, included);
--;;

CREATE TABLE IF NOT EXISTS core.eruption (
    eruption_number       BIGINT PRIMARY KEY,
    volcano_number        INTEGER NOT NULL REFERENCES core.volcano(volcano_number) ON DELETE CASCADE,
    eruption_category     TEXT,
    area_of_activity      TEXT,
    start_year            INTEGER,
    start_month           SMALLINT,
    start_day             SMALLINT,
    end_year              INTEGER,
    end_month             SMALLINT,
    end_day               SMALLINT,
    date_precision        TEXT NOT NULL,
    vei                   NUMERIC(3,1),
    evidence_method       TEXT,
    certainty             TEXT,
    source_dataset_id     BIGINT REFERENCES ops.source_dataset(id),
    source_version        TEXT NOT NULL,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT eruption_start_month CHECK (start_month IS NULL OR start_month BETWEEN 1 AND 12),
    CONSTRAINT eruption_start_day CHECK (start_day IS NULL OR start_day BETWEEN 1 AND 31),
    CONSTRAINT eruption_end_month CHECK (end_month IS NULL OR end_month BETWEEN 1 AND 12),
    CONSTRAINT eruption_end_day CHECK (end_day IS NULL OR end_day BETWEEN 1 AND 31),
    CONSTRAINT eruption_date_precision CHECK
      (date_precision IN ('day', 'month', 'year', 'decade', 'century', 'unknown')),
    CONSTRAINT eruption_vei CHECK (vei IS NULL OR vei BETWEEN 0 AND 8)
);
--;;

CREATE INDEX IF NOT EXISTS eruption_volcano_year_idx
    ON core.eruption (volcano_number, start_year DESC NULLS LAST);
--;;

CREATE TABLE IF NOT EXISTS core.earthquake (
    event_id          TEXT PRIMARY KEY,
    occurred_at       TIMESTAMPTZ NOT NULL,
    updated_at_source TIMESTAMPTZ NOT NULL,
    magnitude         NUMERIC(4,2),
    magnitude_type    TEXT,
    depth_km          NUMERIC(8,3) NOT NULL,
    place             TEXT,
    event_type        TEXT NOT NULL DEFAULT 'earthquake',
    significance      INTEGER,
    tsunami_flag      BOOLEAN NOT NULL DEFAULT false,
    felt_reports      INTEGER,
    alert_level       TEXT,
    status            TEXT,
    detail_url        TEXT,
    geom              geometry(PointZ, 4326) NOT NULL,
    source_dataset_id BIGINT REFERENCES ops.source_dataset(id),
    source_version    TEXT NOT NULL,
    is_deleted        BOOLEAN NOT NULL DEFAULT false,
    ingested_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT earthquake_longitude CHECK (ST_X(geom) BETWEEN -180 AND 180),
    CONSTRAINT earthquake_latitude CHECK (ST_Y(geom) BETWEEN -90 AND 90),
    CONSTRAINT earthquake_depth CHECK (depth_km BETWEEN -10 AND 800)
);
--;;

CREATE INDEX IF NOT EXISTS earthquake_geom_gix ON core.earthquake USING gist (geom);
--;;
CREATE INDEX IF NOT EXISTS earthquake_time_mag_idx
    ON core.earthquake (occurred_at DESC, magnitude DESC NULLS LAST) WHERE NOT is_deleted;
--;;

CREATE TABLE IF NOT EXISTS core.plate_boundary (
    boundary_id       TEXT PRIMARY KEY,
    name              TEXT,
    boundary_type     TEXT NOT NULL,
    description       TEXT,
    geom              geometry(MultiLineString, 4326) NOT NULL,
    source_dataset_id BIGINT REFERENCES ops.source_dataset(id),
    source_version    TEXT NOT NULL,
    source_updated_at TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
--;;

CREATE INDEX IF NOT EXISTS plate_boundary_geom_gix
    ON core.plate_boundary USING gist (geom);
--;;

CREATE TABLE IF NOT EXISTS core.tsunami_event (
    event_id             TEXT PRIMARY KEY,
    event_year           INTEGER,
    event_month          SMALLINT,
    event_day            SMALLINT,
    date_precision       TEXT NOT NULL,
    cause                TEXT,
    country              TEXT,
    location_name        TEXT,
    source_magnitude     NUMERIC(4,1),
    maximum_water_height_m NUMERIC(10,2),
    deaths               INTEGER,
    damage_usd           NUMERIC(18,2),
    validity             TEXT,
    source_confidence    TEXT,
    notes                TEXT,
    geom                 geometry(Point, 4326),
    source_dataset_id    BIGINT REFERENCES ops.source_dataset(id),
    source_version       TEXT NOT NULL,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT tsunami_month CHECK (event_month IS NULL OR event_month BETWEEN 1 AND 12),
    CONSTRAINT tsunami_day CHECK (event_day IS NULL OR event_day BETWEEN 1 AND 31),
    CONSTRAINT tsunami_date_precision CHECK
      (date_precision IN ('day', 'month', 'year', 'decade', 'century', 'unknown'))
);
--;;

CREATE INDEX IF NOT EXISTS tsunami_geom_gix ON core.tsunami_event USING gist (geom);
--;;
CREATE INDEX IF NOT EXISTS tsunami_year_idx ON core.tsunami_event (event_year DESC NULLS LAST);
--;;

CREATE TABLE IF NOT EXISTS core.story_region (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug               TEXT NOT NULL UNIQUE,
    title              TEXT NOT NULL,
    dek                TEXT NOT NULL,
    chapter_order      INTEGER NOT NULL UNIQUE,
    camera_center_lon  NUMERIC(9,6) NOT NULL,
    camera_center_lat  NUMERIC(9,6) NOT NULL,
    camera_zoom        NUMERIC(4,2) NOT NULL,
    route_geom         geometry(MultiLineString, 4326),
    editorial_notes    TEXT,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now()
);
--;;

CREATE TABLE IF NOT EXISTS ops.metabase_resource (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resource_key       TEXT NOT NULL UNIQUE,
    entity_type        TEXT NOT NULL,
    entity_id          INTEGER NOT NULL,
    display_name       TEXT NOT NULL,
    enabled            BOOLEAN NOT NULL DEFAULT true,
    allowed_parameters JSONB NOT NULL DEFAULT '[]'::jsonb,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (entity_type, entity_id),
    CONSTRAINT metabase_entity_type CHECK (entity_type IN ('dashboard', 'question'))
);
--;;

CREATE OR REPLACE VIEW analytics.volcanoes AS
SELECT v.volcano_number,
       v.name,
       v.slug,
       v.country,
       v.subregion,
       r.name AS region,
       v.primary_volcano_type AS volcano_type,
       v.tectonic_setting,
       v.elevation_m,
       v.last_eruption_year,
       ST_Y(v.geom)::double precision AS latitude,
       ST_X(v.geom)::double precision AS longitude,
       rm.included AS in_smithsonian_prof,
       v.source_version
FROM core.volcano v
LEFT JOIN core.volcanic_region r ON r.id = v.volcanic_region_id
LEFT JOIN LATERAL (
  SELECT membership.included
  FROM core.ring_membership membership
  WHERE membership.volcano_number = v.volcano_number
    AND membership.definition_key = 'smithsonian-prof'
  ORDER BY membership.dataset_version DESC
  LIMIT 1
) rm ON true;
--;;

CREATE OR REPLACE VIEW analytics.eruptions AS
SELECT e.eruption_number,
       e.volcano_number,
       v.name AS volcano_name,
       v.country,
       r.name AS region,
       e.start_year,
       e.start_month,
       e.start_day,
       e.date_precision,
       e.vei,
       e.certainty,
       e.source_version
FROM core.eruption e
JOIN core.volcano v USING (volcano_number)
LEFT JOIN core.volcanic_region r ON r.id = v.volcanic_region_id;
--;;

CREATE OR REPLACE VIEW analytics.earthquakes AS
SELECT event_id,
       occurred_at,
       magnitude,
       magnitude_type,
       depth_km,
       place,
       significance,
       tsunami_flag,
       ST_Y(geom)::double precision AS latitude,
       ST_X(geom)::double precision AS longitude,
       source_version
FROM core.earthquake
WHERE NOT is_deleted;
--;;

CREATE OR REPLACE VIEW analytics.tsunamis AS
SELECT event_id,
       event_year,
       event_month,
       event_day,
       date_precision,
       cause,
       country,
       location_name,
       source_magnitude,
       maximum_water_height_m,
       deaths,
       damage_usd,
       validity,
       source_confidence,
       ST_Y(geom)::double precision AS latitude,
       ST_X(geom)::double precision AS longitude,
       source_version
FROM core.tsunami_event;
--;;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'ring_writer') THEN
    CREATE ROLE ring_writer NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'metabase_reader') THEN
    CREATE ROLE metabase_reader NOLOGIN;
  END IF;
END
$$;
--;;

GRANT USAGE ON SCHEMA core, ops, analytics TO ring_writer;
--;;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA core, ops TO ring_writer;
--;;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA core, ops TO ring_writer;
--;;

REVOKE ALL ON SCHEMA core, ops FROM metabase_reader;
--;;
GRANT USAGE ON SCHEMA analytics TO metabase_reader;
--;;
GRANT SELECT ON ALL TABLES IN SCHEMA analytics TO metabase_reader;
--;;
ALTER DEFAULT PRIVILEGES IN SCHEMA analytics GRANT SELECT ON TABLES TO metabase_reader;
